# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170515_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-timestamp', '-updated']},
        ),
    ]
