# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170515_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='imgpath',
            field=models.CharField(default='icharan', max_length=120),
        ),
    ]
